// examples/svelte/create-hotkey-sequence-recorder/src/App.svelte
<script lang="ts">
  import {
    createHotkeySequence,
    createHotkeySequenceRecorder,
    formatForDisplay,
  } from '@tanstack/svelte-hotkeys'
  import type { HotkeySequence } from '@tanstack/svelte-hotkeys'
  import ShortcutListItem from './ShortcutListItem.svelte'

  interface ShortcutActions {
    [key: string]: {
      name: string
      defaultSequence: HotkeySequence
    }
  }

  const DEFAULT_SHORTCUT_ACTIONS = {
    save: {
      name: 'Save',
      defaultSequence: ['Mod+S'],
    },
    open: {
      name: 'Open (gg)',
      defaultSequence: ['G', 'G'],
    },
    new: {
      name: 'New (dd)',
      defaultSequence: ['D', 'D'],
    },
    close: {
      name: 'Close',
      defaultSequence: ['Mod+Shift+K'],
    },
    undo: {
      name: 'Undo (yy)',
      defaultSequence: ['Y', 'Y'],
    },
    redo: {
      name: 'Redo',
      defaultSequence: ['Mod+Shift+G'],
    },
  } as const satisfies ShortcutActions

  let shortcuts = $state<Record<string, HotkeySequence | null>>(
    Object.fromEntries(
      Object.keys(DEFAULT_SHORTCUT_ACTIONS).map((id) => [id, null]),
    ),
  )

  function resolveSeq(actionId: string): HotkeySequence {
    const s = shortcuts[actionId]
    if (s !== null) {
      return s
    }
    return DEFAULT_SHORTCUT_ACTIONS[
      actionId as keyof typeof DEFAULT_SHORTCUT_ACTIONS
    ].defaultSequence
  }

  function formatStat(id: string): string {
    const seq = resolveSeq(id)
    if (seq.length === 0) {
      return '—'
    }
    return seq.map((h) => formatForDisplay(h)).join(' ')
  }

  let saveCount = $state(0)
  let openCount = $state(0)
  let newCount = $state(0)
  let closeCount = $state(0)
  let undoCount = $state(0)
  let redoCount = $state(0)

  let recordingActionId = $state<string | null>(null)

  const recorder = createHotkeySequenceRecorder({
    onRecord: (sequence: HotkeySequence) => {
      if (recordingActionId) {
        shortcuts = {
          ...shortcuts,
          [recordingActionId]: sequence,
        }
        recordingActionId = null
      }
    },
    onCancel: () => {
      recordingActionId = null
    },
    onClear: () => {
      if (recordingActionId) {
        shortcuts = {
          ...shortcuts,
          [recordingActionId]: [],
        }
        recordingActionId = null
      }
    },
  })

  createHotkeySequence(
    () => resolveSeq('save'),
    () => {
      saveCount++
    },
    () => ({
      enabled: !recorder.isRecording && resolveSeq('save').length > 0,
    }),
  )

  createHotkeySequence(
    () => resolveSeq('open'),
    () => {
      openCount++
    },
    () => ({
      enabled: !recorder.isRecording && resolveSeq('open').length > 0,
    }),
  )

  createHotkeySequence(
    () => resolveSeq('new'),
    () => {
      newCount++
    },
    () => ({
      enabled: !recorder.isRecording && resolveSeq('new').length > 0,
    }),
  )

  createHotkeySequence(
    () => resolveSeq('close'),
    () => {
      closeCount++
    },
    () => ({
      enabled: !recorder.isRecording && resolveSeq('close').length > 0,
    }),
  )

  createHotkeySequence(
    () => resolveSeq('undo'),
    () => {
      undoCount++
    },
    () => ({
      enabled: !recorder.isRecording && resolveSeq('undo').length > 0,
    }),
  )

  createHotkeySequence(
    () => resolveSeq('redo'),
    () => {
      redoCount++
    },
    () => ({
      enabled: !recorder.isRecording && resolveSeq('redo').length > 0,
    }),
  )

  function handleEdit(actionId: string) {
    recordingActionId = actionId
    recorder.startRecording()
  }

  function handleCancel() {
    recorder.cancelRecording()
    recordingActionId = null
  }
</script>

<div class="app">
  <header>
    <h1>Sequence shortcut settings</h1>
    <p>
      Customize Vim-style sequences. Click Edit, press each chord in order, then
      Enter to save. Escape cancels; Backspace removes the last chord or clears
      when empty.
    </p>
  </header>

  <main>
    <section class="demo-section">
      <h2>Shortcuts</h2>
      <div class="shortcuts-list">
        {#each Object.entries(DEFAULT_SHORTCUT_ACTIONS) as [actionId, action]}
          <ShortcutListItem
            actionName={action.name}
            sequence={resolveSeq(actionId)}
            disabled={resolveSeq(actionId).length === 0}
            liveSteps={recorder.steps}
            isRecording={recorder.isRecording && recordingActionId === actionId}
            onEdit={() => handleEdit(actionId)}
            onCancel={handleCancel}
          />
        {/each}
      </div>
    </section>

    <section class="demo-section">
      <h2>Demo actions</h2>
      <p>Try your sequences within the default timeout window.</p>
      <div class="demo-stats">
        <div class="stat-item">
          <div class="stat-label">Save</div>
          <div class="stat-value">{saveCount}</div>
          <kbd>{formatStat('save')}</kbd>
        </div>
        <div class="stat-item">
          <div class="stat-label">Open</div>
          <div class="stat-value">{openCount}</div>
          <kbd>{formatStat('open')}</kbd>
        </div>
        <div class="stat-item">
          <div class="stat-label">New</div>
          <div class="stat-value">{newCount}</div>
          <kbd>{formatStat('new')}</kbd>
        </div>
        <div class="stat-item">
          <div class="stat-label">Close</div>
          <div class="stat-value">{closeCount}</div>
          <kbd>{formatStat('close')}</kbd>
        </div>
        <div class="stat-item">
          <div class="stat-label">Undo</div>
          <div class="stat-value">{undoCount}</div>
          <kbd>{formatStat('undo')}</kbd>
        </div>
        <div class="stat-item">
          <div class="stat-label">Redo</div>
          <div class="stat-value">{redoCount}</div>
          <kbd>{formatStat('redo')}</kbd>
        </div>
      </div>
    </section>

    {#if recorder.isRecording}
      <div class="info-box recording-notice">
        <strong>Recording sequence…</strong> Press each chord, then Enter to
        finish. Escape cancels. Backspace removes the last chord or clears.
        {#if recorder.steps.length > 0}
          <div>
            Steps: {recorder.steps.map((h) => formatForDisplay(h)).join(' ')}
          </div>
        {/if}
      </div>
    {/if}

    <section class="demo-section">
      <h2>Usage</h2>
      <pre class="code-block">{`import {
  createHotkeySequence,
  createHotkeySequenceRecorder,
} from '@tanstack/svelte-hotkeys'

createHotkeySequence(['G', 'G'], () => goTop(), () => ({
  enabled: !recorder.isRecording,
}))`}</pre>
    </section>
  </main>
</div>

// examples/angular/injectHotkeySequenceRecorder/src/app/app.component.ts
import { Component, signal } from '@angular/core'
import {
  formatForDisplay,
  injectHotkeySequence,
  injectHotkeySequenceRecorder,
} from '@tanstack/angular-hotkeys'
import type { HotkeySequence } from '@tanstack/angular-hotkeys'
import { ShortcutListItemComponent } from './shortcut-list-item.component'

const DEFAULT_SHORTCUT_ACTIONS: Record<
  string,
  { name: string; defaultSequence: HotkeySequence }
> = {
  save: { name: 'Save', defaultSequence: ['Mod+S'] },
  open: { name: 'Open (gg)', defaultSequence: ['G', 'G'] },
  new: { name: 'New (dd)', defaultSequence: ['D', 'D'] },
  close: { name: 'Close', defaultSequence: ['Mod+Shift+K'] },
  undo: { name: 'Undo (yy)', defaultSequence: ['Y', 'Y'] },
  redo: { name: 'Redo', defaultSequence: ['Mod+Shift+G'] },
}

const ACTION_ENTRIES = Object.entries(DEFAULT_SHORTCUT_ACTIONS)

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [ShortcutListItemComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  private readonly recorder = injectHotkeySequenceRecorder({
    onRecord: (sequence: HotkeySequence) => {
      const id = this.recordingActionId()
      if (id) {
        this.shortcuts.update((prev) => ({
          ...prev,
          [id]: sequence,
        }))
        this.recordingActionId.set(null)
      }
    },
    onCancel: () => this.recordingActionId.set(null),
    onClear: () => {
      const id = this.recordingActionId()
      if (id) {
        this.shortcuts.update((prev) => ({ ...prev, [id]: [] }))
        this.recordingActionId.set(null)
      }
    },
  })

  shortcuts = signal<Record<string, HotkeySequence | null>>(
    Object.fromEntries(
      Object.keys(DEFAULT_SHORTCUT_ACTIONS).map((id) => [id, null]),
    ) as Record<string, HotkeySequence | null>,
  )

  saveCount = signal(0)
  openCount = signal(0)
  newCount = signal(0)
  closeCount = signal(0)
  undoCount = signal(0)
  redoCount = signal(0)
  recordingActionId = signal<string | null>(null)

  readonly actionEntries = ACTION_ENTRIES
  readonly defaultActions = DEFAULT_SHORTCUT_ACTIONS
  formatForDisplay = formatForDisplay

  constructor() {
    injectHotkeySequence(
      () => this.resolveSeq('save'),
      () => this.saveCount.update((c) => c + 1),
      () => ({
        enabled:
          !this.recorder.isRecording() && this.resolveSeq('save').length > 0,
      }),
    )
    injectHotkeySequence(
      () => this.resolveSeq('open'),
      () => this.openCount.update((c) => c + 1),
      () => ({
        enabled:
          !this.recorder.isRecording() && this.resolveSeq('open').length > 0,
      }),
    )
    injectHotkeySequence(
      () => this.resolveSeq('new'),
      () => this.newCount.update((c) => c + 1),
      () => ({
        enabled:
          !this.recorder.isRecording() && this.resolveSeq('new').length > 0,
      }),
    )
    injectHotkeySequence(
      () => this.resolveSeq('close'),
      () => this.closeCount.update((c) => c + 1),
      () => ({
        enabled:
          !this.recorder.isRecording() && this.resolveSeq('close').length > 0,
      }),
    )
    injectHotkeySequence(
      () => this.resolveSeq('undo'),
      () => this.undoCount.update((c) => c + 1),
      () => ({
        enabled:
          !this.recorder.isRecording() && this.resolveSeq('undo').length > 0,
      }),
    )
    injectHotkeySequence(
      () => this.resolveSeq('redo'),
      () => this.redoCount.update((c) => c + 1),
      () => ({
        enabled:
          !this.recorder.isRecording() && this.resolveSeq('redo').length > 0,
      }),
    )
  }

  readonly isRecording = this.recorder.isRecording
  readonly recorderSteps = this.recorder.steps

  resolveSeq(id: string): HotkeySequence {
    const s = this.shortcuts()[id]
    if (s !== null) {
      return s
    }
    return this.defaultActions[id]!.defaultSequence
  }

  handleEdit(actionId: string): void {
    this.recordingActionId.set(actionId)
    this.recorder.startRecording()
  }

  handleCancel(): void {
    this.recorder.cancelRecording()
    this.recordingActionId.set(null)
  }

  sequenceStatLabel(id: string): string {
    const seq = this.resolveSeq(id)
    if (seq.length === 0) {
      return '—'
    }
    return seq.map((h) => this.formatForDisplay(h)).join(' ')
  }

  recordingStepsLabel(): string {
    return this.recorder
      .steps()
      .map((h) => this.formatForDisplay(h))
      .join(' ')
  }

  countFor(id: string): number {
    const counts: Record<string, () => number> = {
      save: () => this.saveCount(),
      open: () => this.openCount(),
      new: () => this.newCount(),
      close: () => this.closeCount(),
      undo: () => this.undoCount(),
      redo: () => this.redoCount(),
    }
    return counts[id]?.() ?? 0
  }
}

<div class="app">
  <header>
    <h1>Sequence shortcut settings</h1>
    <p>
      Customize Vim-style sequences. Click Edit, press each chord in order, then
      Enter to save. Escape cancels; Backspace removes the last chord or clears
      when empty.
    </p>
  </header>

  <main>
    <section class="demo-section">
      <h2>Shortcuts</h2>
      <div class="shortcuts-list">
        @for (entry of actionEntries; track entry[0]) {
          <app-shortcut-list-item
            [actionName]="entry[1].name"
            [sequence]="resolveSeq(entry[0])"
            [disabled]="resolveSeq(entry[0]).length === 0"
            [liveSteps]="recorderSteps()"
            [isRecording]="isRecording() && recordingActionId() === entry[0]"
            (edit)="handleEdit(entry[0])"
            (cancel)="handleCancel()"
          />
        }
      </div>
    </section>

    <section class="demo-section">
      <h2>Demo actions</h2>
      <p>Try your sequences within the default timeout window.</p>
      <div class="demo-stats">
        @for (entry of actionEntries; track entry[0]) {
          <div class="stat-item">
            <div class="stat-label">{{ entry[1].name }}</div>
            <div class="stat-value">{{ countFor(entry[0]) }}</div>
            <kbd>{{ sequenceStatLabel(entry[0]) }}</kbd>
          </div>
        }
      </div>
    </section>

    @if (isRecording()) {
      <div class="info-box recording-notice">
        <strong>Recording sequence…</strong> Press each chord, then Enter to
        finish. Escape cancels. Backspace removes the last chord or clears.
        @if (recorderSteps().length > 0) {
          <div>Steps: {{ recordingStepsLabel() }}</div>
        }
      </div>
    }

    <section class="demo-section">
      <h2>Usage</h2>
      <pre class="code-block">
import {{ '{' }} injectHotkeySequence, injectHotkeySequenceRecorder {{
          '}'
        }} from '&#64;tanstack/angular-hotkeys'

injectHotkeySequence(['G', 'G'], () => this.goTop(), () => ({{
          '{'
        }} enabled: !this.recorder.isRecording() {{ '}' }}))</pre
      >
    </section>
  </main>
</div>
