// examples/vue/useHotkeySequenceRecorder/src/ShortcutListItem.vue
<script setup lang="ts">
import { formatForDisplay, useHeldKeys } from '@tanstack/vue-hotkeys'
import type { HotkeySequence } from '@tanstack/vue-hotkeys'

defineEmits<{
  edit: []
  cancel: []
}>()

defineProps<{
  actionName: string
  sequence: HotkeySequence
  disabled: boolean
  isRecording: boolean
  liveSteps: HotkeySequence
}>()

const heldKeys = useHeldKeys()

function formatSeq(seq: HotkeySequence): string {
  return seq.map((h) => formatForDisplay(h)).join(' ')
}
</script>

<template>
  <div class="shortcut-item" :class="{ recording: isRecording }">
    <div class="shortcut-item-content">
      <div class="shortcut-action">{{ actionName }}</div>
      <div class="shortcut-hotkey">
        <div v-if="isRecording" class="recording-indicator">
          <span v-if="liveSteps.length > 0" class="held-hotkeys">{{
            formatSeq(liveSteps)
          }}</span>
          <div v-else-if="heldKeys.length > 0" class="held-hotkeys">
            <template v-for="(key, index) in heldKeys" :key="key">
              <span v-if="index > 0" class="plus">+</span>
              <kbd>{{ key }}</kbd>
            </template>
          </div>
          <span v-else class="recording-text">Press chords, then Enter…</span>
        </div>
        <kbd v-else-if="!disabled">{{ formatSeq(sequence) }}</kbd>
        <span v-else class="no-shortcut">No shortcut</span>
      </div>
    </div>
    <div class="shortcut-actions">
      <button
        v-if="isRecording"
        type="button"
        class="cancel-button"
        @click="$emit('cancel')"
      >
        Cancel
      </button>
      <button v-else type="button" class="edit-button" @click="$emit('edit')">
        Edit
      </button>
    </div>
  </div>
</template>

// examples/angular/injectHotkeySequenceRecorder/src/app/shortcut-list-item.component.ts
import { Component, input, output } from '@angular/core'
import {
  formatForDisplay,
  injectHeldKeys,
  type HotkeySequence,
} from '@tanstack/angular-hotkeys'

@Component({
  selector: 'app-shortcut-list-item',
  standalone: true,
  templateUrl: './shortcut-list-item.component.html',
  styleUrl: './shortcut-list-item.component.css',
})
export class ShortcutListItemComponent {
  actionName = input.required<string>()
  sequence = input.required<HotkeySequence>()
  disabled = input.required<boolean>()
  liveSteps = input.required<HotkeySequence>()
  isRecording = input.required<boolean>()
  edit = output<void>()
  cancel = output<void>()

  heldKeys = injectHeldKeys()
  readonly formatForDisplay = formatForDisplay

  formatSeq(seq: HotkeySequence): string {
    return seq.map((h) => formatForDisplay(h)).join(' ')
  }
}

<div class="shortcut-item" [class.recording]="isRecording()">
  <div class="shortcut-item-content">
    <div class="shortcut-action">{{ actionName() }}</div>
    <div class="shortcut-hotkey">
      @if (isRecording()) {
        <div class="recording-indicator">
          @if (liveSteps().length > 0) {
            <span class="held-hotkeys">{{ formatSeq(liveSteps()) }}</span>
          } @else if (heldKeys().length > 0) {
            <div class="held-hotkeys">
              @for (key of heldKeys(); track key; let i = $index) {
                @if (i > 0) {
                  <span class="plus">+</span>
                }
                <kbd>{{ formatForDisplay(key, { useSymbols: true }) }}</kbd>
              }
            </div>
          } @else {
            <span class="recording-text">Press chords, then Enter…</span>
          }
        </div>
      } @else if (!disabled()) {
        <kbd>{{ formatSeq(sequence()) }}</kbd>
      } @else {
        <span class="no-shortcut">No shortcut</span>
      }
    </div>
  </div>
  <div class="shortcut-actions">
    @if (isRecording()) {
      <button type="button" class="cancel-button" (click)="cancel.emit()">
        Cancel
      </button>
    } @else {
      <button type="button" class="edit-button" (click)="edit.emit()">
        Edit
      </button>
    }
  </div>
</div>
