// examples/vue/useHotkeySequenceRecorder/src/ShortcutListItem.vue
<script setup lang="ts">
import { formatForDisplay, useHeldKeys } from '@tanstack/vue-hotkeys'
import type { HotkeySequence } from '@tanstack/vue-hotkeys'

defineEmits<{
  edit: []
  cancel: []
}>()

defineProps<{
  actionName: string
  sequence: HotkeySequence
  disabled: boolean
  isRecording: boolean
  liveSteps: HotkeySequence
}>()

const heldKeys = useHeldKeys()

function formatSeq(seq: HotkeySequence): string {
  return seq.map((h) => formatForDisplay(h)).join(' ')
}
</script>

<template>
  <div class="shortcut-item" :class="{ recording: isRecording }">
    <div class="shortcut-item-content">
      <div class="shortcut-action">{{ actionName }}</div>
      <div class="shortcut-hotkey">
        <div v-if="isRecording" class="recording-indicator">
          <span v-if="liveSteps.length > 0" class="held-hotkeys">{{
            formatSeq(liveSteps)
          }}</span>
          <div v-else-if="heldKeys.length > 0" class="held-hotkeys">
            <template v-for="(key, index) in heldKeys" :key="key">
              <span v-if="index > 0" class="plus">+</span>
              <kbd>{{ key }}</kbd>
            </template>
          </div>
          <span v-else class="recording-text">Press chords, then Enter…</span>
        </div>
        <kbd v-else-if="!disabled">{{ formatSeq(sequence) }}</kbd>
        <span v-else class="no-shortcut">No shortcut</span>
      </div>
    </div>
    <div class="shortcut-actions">
      <button
        v-if="isRecording"
        type="button"
        class="cancel-button"
        @click="$emit('cancel')"
      >
        Cancel
      </button>
      <button v-else type="button" class="edit-button" @click="$emit('edit')">
        Edit
      </button>
    </div>
  </div>
</template>

// examples/svelte/create-hotkey-sequence-recorder/src/ShortcutListItem.svelte
<script lang="ts">
  import { formatForDisplay, getHeldKeys } from '@tanstack/svelte-hotkeys'
  import type { HotkeySequence } from '@tanstack/svelte-hotkeys'

  interface Props {
    actionName: string
    sequence: HotkeySequence
    disabled: boolean
    liveSteps: HotkeySequence
    isRecording: boolean
    onEdit: () => void
    onCancel: () => void
  }

  let {
    actionName,
    sequence,
    disabled,
    liveSteps,
    isRecording,
    onEdit,
    onCancel,
  }: Props = $props()

  const heldKeys = getHeldKeys()

  function formatSeq(seq: HotkeySequence): string {
    return seq.map((h) => formatForDisplay(h)).join(' ')
  }
</script>

<div class="shortcut-item" class:recording={isRecording}>
  <div class="shortcut-item-content">
    <div class="shortcut-action">{actionName}</div>
    <div class="shortcut-hotkey">
      {#if isRecording}
        <div class="recording-indicator">
          {#if liveSteps.length > 0}
            <span class="held-hotkeys">{formatSeq(liveSteps)}</span>
          {:else if heldKeys.keys.length > 0}
            <div class="held-hotkeys">
              {#each heldKeys.keys as key, index}
                {#if index > 0}
                  <span class="plus">+</span>
                {/if}
                <kbd>{key}</kbd>
              {/each}
            </div>
          {:else}
            <span class="recording-text">Press chords, then Enter…</span>
          {/if}
        </div>
      {:else if !disabled}
        <kbd>{formatSeq(sequence)}</kbd>
      {:else}
        <span class="no-shortcut">No shortcut</span>
      {/if}
    </div>
  </div>
  <div class="shortcut-actions">
    {#if isRecording}
      <button type="button" onclick={onCancel} class="cancel-button">
        Cancel
      </button>
    {:else}
      <button type="button" onclick={onEdit} class="edit-button">Edit</button>
    {/if}
  </div>
</div>
